services:
  pg:
    image: postgres:latest
    container_name: postgres
    env_file:
      - /server/.env
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - /usr/src/app/node_modules
      - ./server:/usr/src/app
    depends_on:
      - pg
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - server
    ports:
      - "3000:3000"

networks:
  myNet:
    driver: bridge

volumes:
  pg:
    driver: local
